import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const vaultPluginDir =
	process.env.OBSIDIPI_VAULT_PLUGIN_DIR
	?? join(homedir(), "Documents/notes/.obsidian/plugins/obsidipi");

const repoRoot = dirname(new URL(import.meta.url).pathname);

const copyToVaultPlugin = {
	name: "copy-to-vault-plugin",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			if (!existsSync(vaultPluginDir)) {
				console.log(`[copy-to-vault] skip: ${vaultPluginDir} does not exist`);
				return;
			}
			mkdirSync(vaultPluginDir, { recursive: true });
			for (const file of ["main.js", "styles.css", "manifest.json"]) {
				const src = join(repoRoot, file);
				if (!existsSync(src)) continue;
				copyFileSync(src, join(vaultPluginDir, file));
			}
			console.log(`[copy-to-vault] copied → ${vaultPluginDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
